import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#0a0e27', paddingTop: 0 },
    scrollView: { flex: 1, paddingBottom: 16 },
    header: { padding: 16, paddingTop: 40, paddingBottom: 20, backgroundColor: '#0a0e27', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 5 },
    headerTitle: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
    title: { fontSize: 28, fontWeight: '800', color: '#ffffff', flex: 1, letterSpacing: -0.5 },
    subtitle: { fontSize: 12, fontWeight: '500', color: '#a0aec0', marginTop: 4, fontStyle: 'italic' },
    headerButtons: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end' },
    monthButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#1a2247', padding: 12, borderRadius: 12, marginRight: 4 },
    monthButtonText: { color: '#a0aec0', fontWeight: '600', fontSize: 13 },
    exportButton: { backgroundColor: '#1a2247', padding: 12, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginLeft: 4 },
    statsContainer: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 14, paddingVertical: 16, gap: 12, marginBottom: 8 },
    statCard: { width: '48%', padding: 16, borderRadius: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 8, elevation: 5 },
    expenseCard: { backgroundColor: '#2d1619' },
    incomeCard: { backgroundColor: '#1a2e1a' },
    balanceCard: { backgroundColor: '#162644' },
    totalCard: { backgroundColor: '#2d1f3d' },
    statLabel: { color: '#a0aec0', fontSize: 12, marginBottom: 6, fontWeight: '500' },
    statValue: { color: '#ffffff', fontSize: 20, fontWeight: '800' },
    categoryContainer: { marginHorizontal: 14, marginVertical: 12, paddingHorizontal: 14, paddingVertical: 16, borderRadius: 16, backgroundColor: '#1a2247', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 3 },
    categoryTitle: { color: '#e2e8f0', fontSize: 14, fontWeight: '700', marginBottom: 14 },
    categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    categoryItem: { width: '48%', padding: 13, borderRadius: 12, backgroundColor: '#243156', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.15, shadowRadius: 4, elevation: 2 },
    categoryName: { color: '#a0aec0', fontSize: 12, fontWeight: '500' },
    categoryAmount: { color: '#ffffff', fontSize: 15, fontWeight: '800', marginTop: 6 },
    categoryPercent: { color: '#718096', fontSize: 11, marginTop: 4 },
    addButton: { marginHorizontal: 14, marginVertical: 12, borderRadius: 14, overflow: 'hidden' },
    addButtonGradient: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 16, paddingHorizontal: 16, borderRadius: 14, backgroundColor: '#3b82f6' },
    addButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
    formContainer: { marginHorizontal: 14, marginVertical: 12, paddingHorizontal: 16, paddingVertical: 18, borderRadius: 16, backgroundColor: '#1a2247', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 3 },
    formTitle: { fontSize: 17, fontWeight: '700', color: '#ffffff', marginBottom: 16 },
    typeSelector: { flexDirection: 'row', gap: 10, marginBottom: 14 },
    typeButton: { flex: 1, padding: 12, borderRadius: 10, backgroundColor: '#243156', alignItems: 'center' },
    typeButtonActive: { backgroundColor: '#ef4444' },
    typeButtonActiveIncome: { backgroundColor: '#10b981' },
    typeText: { color: '#a0aec0', fontWeight: '600', fontSize: 13 },
    typeTextActive: { color: '#ffffff', fontWeight: '600', fontSize: 13 },
    checkboxContainer: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#243156', padding: 12, borderRadius: 10, marginBottom: 14 },
    checkboxLabel: { color: '#e2e8f0', fontWeight: '600', fontSize: 13 },
    label: { color: '#e2e8f0', fontSize: 13, fontWeight: '600', marginBottom: 8, marginTop: 10 },
    inputWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#243156', borderWidth: 1, borderColor: '#334a6e', borderRadius: 10, paddingHorizontal: 12 },
    input: { flex: 1, backgroundColor: '#243156', borderWidth: 1, borderColor: '#334a6e', borderRadius: 10, padding: 12, color: '#ffffff', fontSize: 15, marginBottom: 0 },
    suggestionItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#334a6e' },
    suggestionDesc: { color: '#ffffff', fontWeight: '600', fontSize: 13 },
    suggestionMeta: { color: '#a0aec0', fontSize: 12, marginTop: 2 },
    frequencyButtons: { flexDirection: 'row', gap: 8, marginBottom: 14 },
    freqButton: { flex: 1, padding: 11, backgroundColor: '#243156', borderRadius: 10, alignItems: 'center' },
    freqButtonActive: { backgroundColor: '#3b82f6' },
    freqButtonText: { color: '#a0aec0', fontWeight: '600', fontSize: 12 },
    freqButtonTextActive: { color: '#ffffff', fontWeight: '600', fontSize: 12 },
    categoryChip: { backgroundColor: '#243156', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18, marginRight: 8, borderWidth: 0 },
    categoryChipActive: { backgroundColor: '#3b82f6' },
    categoryChipText: { color: '#a0aec0', fontSize: 12, fontWeight: '500' },
    categoryChipTextActive: { color: '#ffffff', fontWeight: '600', fontSize: 12 },
    saveButton: { backgroundColor: '#10b981', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 15, borderRadius: 12, marginTop: 14 },
    saveButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
    cancelButton: { backgroundColor: '#243156', padding: 12, borderRadius: 10, marginTop: 10, alignItems: 'center' },
    cancelButtonText: { color: '#a0aec0', fontSize: 14, fontWeight: '600' },
    tabsContainer: { flexDirection: 'row', paddingHorizontal: 14, paddingVertical: 10, gap: 8, marginBottom: 8 },
    tab: { flex: 1, flexDirection: 'row', paddingVertical: 11, paddingHorizontal: 10, borderRadius: 12, backgroundColor: '#1a2247', alignItems: 'center', justifyContent: 'center', gap: 6 },
    tabActive: { backgroundColor: '#3b82f6' },
    tabText: { color: '#a0aec0', fontWeight: '600', fontSize: 11 },
    tabTextActive: { color: '#ffffff', fontWeight: '700', fontSize: 11 },
    listContainer: { paddingHorizontal: 14, paddingVertical: 8 },
    transactionItem: { borderWidth: 0, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, marginBottom: 10, marginHorizontal: 0, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#1a2247', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4, elevation: 2 },
    txLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 11 },
    txDate: { color: '#a0aec0', fontSize: 12, fontWeight: '500', minWidth: 50 },
    txDesc: { color: '#ffffff', fontSize: 14, fontWeight: '600' },
    txCat: { color: '#a0aec0', fontSize: 12, marginTop: 3 },
    txRight: { alignItems: 'flex-end' },
    txAmount: { color: '#ff6b6b', fontSize: 15, fontWeight: '800', marginBottom: 4 },
    txIncomeAmount: { color: '#51cf66' },
    txActions: { flexDirection: 'row', gap: 8 },
    recFreq: { color: '#a78bfa', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', minWidth: 50 },
    emptyText: { color: '#a0aec0', fontSize: 16, textAlign: 'center', paddingVertical: 40 },
    emptyContainer: { alignItems: 'center', paddingVertical: 60 },
    insightCard: { borderWidth: 0, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 14, marginHorizontal: 14, marginBottom: 10, backgroundColor: '#1a2247', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4, elevation: 2 },
    insightLabel: { color: '#e2e8f0', fontWeight: '600', fontSize: 13, marginBottom: 10 },
    insightRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' },
    insightSmall: { color: '#a0aec0', fontSize: 12 },
    insightBig: { color: '#ffffff', fontSize: 20, fontWeight: '800', marginTop: 4 },
    insightDelta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    insightDeltaText: { fontWeight: '700', fontSize: 13 },
    changeItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#334a6e' },
    changeCat: { color: '#ffffff', fontWeight: '600', fontSize: 13 },
    changeMeta: { color: '#a0aec0', fontSize: 12, marginTop: 2 },
    changePercent: { fontWeight: '700', fontSize: 13 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
    modalContent: { borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingTop: 24, paddingHorizontal: 18, paddingBottom: 28, maxHeight: '90%', backgroundColor: '#1a2247', borderTopWidth: 0, shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.3, shadowRadius: 12, elevation: 8 },
    modalTitle: { fontSize: 20, fontWeight: '800', color: '#ffffff', marginBottom: 18 },
    monthOption: { paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#334a6e' },
    monthOptionText: { color: '#e2e8f0', fontSize: 15, fontWeight: '500' },
    closeButton: { backgroundColor: '#243156', padding: 13, borderRadius: 10, marginTop: 12, alignItems: 'center' },
    closeButtonText: { color: '#a0aec0', fontSize: 14, fontWeight: '600' },
});
